---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: anarchyapis.gpte.redhat.com
spec:
  group: gpte.redhat.com
  version: v1
  scope: Namespaced
  names:
    plural: anarchyapis
    singular: anarchyapi
    kind: AnarchyAPI
    shortNames: []
  subresources:
    status: {}
