---
apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition
metadata:
  name: anarchysubjects.gpte.redhat.com
spec:
  group: gpte.redhat.com
  version: v1 
  scope: Namespaced 
  names:
    plural: anarchysubjects
    singular: anarchysubject
    kind: AnarchySubject
    shortNames: []
