---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: anarchyactions.gpte.redhat.com
spec:
  group: gpte.redhat.com
  version: v1
  scope: Namespaced
  names:
    plural: anarchyactions
    singular: anarchyaction
    kind: AnarchyAction
    shortNames: []
  subresources:
    status: {}
