---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: anarchygovernors.gpte.redhat.com
spec:
  group: gpte.redhat.com
  version: v1
  scope: Namespaced
  names:
    plural: anarchygovernors
    singular: anarchygovernor
    kind: AnarchyGovernor
    shortNames: []
  subresources:
    status: {}
