---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Build resources for anarchy
  name: anarchy-build

parameters:
- name: KOPF_S2I_IMAGE
  value: quay.io/redhat-cop/python-kopf-s2i:v0.28
- name: RUNNER_BASE_IMAGE
  value: registry.access.redhat.com/ubi8/python-38:latest
- name: GIT_REPO
  value: https://github.com/redhat-cop/anarchy.git
- name: NAME
  value: anarchy

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${NAME}-runner
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: operator
      git:
        uri: ${GIT_REPO}
        ref: master
    strategy:
      type: Source
      sourceStrategy:
        forcePull: true
        from:
          kind: DockerImage
          name: ${KOPF_S2I_IMAGE}
    triggers: []

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}-runner
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-runner:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: anarchy-runner
      git:
        uri: ${GIT_REPO}
        ref: master
    strategy:
      type: Docker
      dockerStrategy:
        forcePull: true
        from:
          kind: DockerImage
          name: ${RUNNER_BASE_IMAGE}
    triggers: []
