---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Build resources for anarchy-operator
  name: anarchy-operator-build

parameters:
- name: GIT_REPO
  value: https://github.com/redhat-gpte-devopsautomation/anarchy-operator.git
- name: NAMESPACE
  value: anarchy-operator

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: anarchy-operator
    namespace: ${NAMESPACE}
  spec:
    lookupPolicy:
      local: false

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: anarchy-ansible-runner
    namespace: ${NAMESPACE}
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: anarchy-operator
    namespace: ${NAMESPACE}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: anarchy-operator:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: operator
      git:
        uri: ${GIT_REPO}
        ref: master
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: DockerImage
          name: registry.access.redhat.com/ubi8/python-36:latest
    triggers: []

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: anarchy-ansible-runner
    namespace: ${NAMESPACE}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: anarchy-ansible-runner:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: ansible-runner
      git:
        uri: ${GIT_REPO}
        ref: master
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: DockerImage
          name: registry.access.redhat.com/ubi8/python-36:latest
    triggers: []
