---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: anarchy-operator deploy
  name: anarchy-operator-deploy

parameters:
- name: ANARCHY_NAMESPACE
  value: anarchy-operator
- name: ANARCHY_IMAGE
  value: quay.io/gpte-devops-automation/anarchy-operator:0.1.7
  #value: docker-registry.default.svc:5000/anarchy-operator/anarchy-operator:latest
  #value: image-registry.openshift-image-registry.svc:5000/anarchy-operator/anarchy-operator:latest
- name: ANSIBLE_RUNNER_IMAGE
  value: quay.io/gpte-devops-automation/anarchy-ansible-runner:0.1.7
  #value: docker-registry.default.svc:5000/anarchy-operator/anarchy-ansible-runner:latest
  #value: image-registry.openshift-image-registry.svc:5000/anarchy-operator/anarchy-operator:latest
- name: ANARCHY_SERVICE_NAME
  value: anarchy-operator
- name: APP_DOMAIN
  required: true

objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: ${ANARCHY_NAMESPACE}
    annotations:
      openshift-provision/action: create

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${ANARCHY_SERVICE_NAME}
    namespace: ${ANARCHY_NAMESPACE}

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: ${ANARCHY_SERVICE_NAME}-edit
    namespace: ${ANARCHY_NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: ServiceAccount
    name: ${ANARCHY_SERVICE_NAME}
    namespace: ${ANARCHY_NAMESPACE}

- apiVersion: v1
  kind: Service
  metadata:
    name: ${ANARCHY_SERVICE_NAME}
    namespace: ${ANARCHY_NAMESPACE}
  spec:
    ports:
    - name: api
      port: 5000
      protocol: TCP
      targetPort: 5000
    - name: metrics
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      name: ${ANARCHY_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Route
  metadata:
    name: ${ANARCHY_SERVICE_NAME}
    namespace: ${ANARCHY_NAMESPACE}
  spec:
    host: ${ANARCHY_NAMESPACE}.${APP_DOMAIN}
    port:
      targetPort: api
    tls:
      termination: edge
    to:
      kind: Service
      name: ${ANARCHY_SERVICE_NAME}
      weight: 100
    wildcardPolicy: None

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: ${ANARCHY_SERVICE_NAME}
    name: ${ANARCHY_SERVICE_NAME}
    namespace: ${ANARCHY_NAMESPACE}
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: ${ANARCHY_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${ANARCHY_SERVICE_NAME}
      spec:
        containers:
        - name: manager
          env:
          - name: ANSIBLE_RUNNER_IMAGE
            value: ${ANSIBLE_RUNNER_IMAGE}
          - name: CALLBACK_BASE_URL
            value: https://${ANARCHY_NAMESPACE}.${APP_DOMAIN}
          image: ${ANARCHY_IMAGE}
          imagePullPolicy: IfNotPresent
          # FIXME - Add probes
          #livenessProbe:
          #readinessProbe:
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        restartPolicy: Always
        securityContext: {}
        serviceAccountName: ${ANARCHY_SERVICE_NAME}
        terminationGracePeriodSeconds: 30

- kind: ClusterRole
  apiVersion: v1
  metadata:
    name: anarchy-operator
  rules:
  - apiGroups:
    - anarchy.gpte.redhat.com
    resources:
    - anarchyapis
    - anarchygovernors
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - anarchy.gpte.redhat.com
    resources:
    - anarchysubjects
    verbs:
    - get
    - list
    - watch
    - update
    - patch
    - delete
  - apiGroups:
    - anarchy.gpte.redhat.com
    resources:
    - anarchyactions
    - anarchyactions/status
    - anarchysubjects/status
    verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
    - update

- kind: ClusterRole
  apiVersion: v1
  metadata:
    name: admin-anarchy-subjects
  rules:
  - apiGroups:
    - anarchy.gpte.redhat.com
    resources:
    - anarchysubjects
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - watch
  - apiGroups:
    - anarchy.gpte.redhat.com
    resources:
    - anarchyactions
    - anarchyactions/status
    - anarchysubjects/status
    verbs:
    - get
    - list
    - watch

- kind: ClusterRoleBinding
  apiVersion: v1
  metadata:
    name: anarchy-operator:${ANARCHY_NAMESPACE}:${ANARCHY_SERVICE_NAME}
  roleRef:
    name: anarchy-operator
  subjects:
  - kind: ServiceAccount
    namespace: ${ANARCHY_NAMESPACE}
    name: ${ANARCHY_SERVICE_NAME}

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: anarchyapis.anarchy.gpte.redhat.com
  spec:
    group: anarchy.gpte.redhat.com
    version: v1
    scope: Namespaced
    names:
      plural: anarchyapis
      singular: anarchyapi
      kind: AnarchyAPI
      shortNames: []
    subresources:
      status: {}

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: anarchygovernors.anarchy.gpte.redhat.com
  spec:
    group: anarchy.gpte.redhat.com
    version: v1
    scope: Namespaced
    names:
      plural: anarchygovernors
      singular: anarchygovernor
      kind: AnarchyGovernor
      shortNames: []
    subresources:
      status: {}

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: anarchysubjects.anarchy.gpte.redhat.com
  spec:
    group: anarchy.gpte.redhat.com
    version: v1
    scope: Namespaced
    names:
      plural: anarchysubjects
      singular: anarchysubject
      kind: AnarchySubject
      shortNames: []
    subresources:
      status: {}

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: anarchyactions.anarchy.gpte.redhat.com
  spec:
    group: anarchy.gpte.redhat.com
    version: v1
    scope: Namespaced
    names:
      plural: anarchyactions
      singular: anarchyaction
      kind: AnarchyAction
      shortNames: []
    subresources:
      status: {}
