---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: anarchy-operator deploy
  name: anarchy-operator-deploy

parameters:
- name: NAME
  description: Name for Anarchy resources
  displayName: Name
  value: anarchy-operator
- name: OPERATOR_DOMAIN
  description: Anarchy operator custom resource definition domain
  displayName: Anarchy operator CRD domain
  value: anarchy.gpte.redhat.com
- name: OPERATOR_HOSTNAME
  displayName: Operator Hostname
  description: Hostname for callback API route
  required: True
- name: OPERATOR_IMAGE
  value: quay.io/redhat-cop/anarchy:v0.4.0
  #value: docker-registry.default.svc:5000/anarchy-operator/anarchy:latest
  #value: image-registry.openshift-image-registry.svc:5000/anarchy-operator/anarchy:latest
- name: OPERATOR_IMAGE_PULL_POLICY
  value: IfNotPresent
  #value: Always
- name: RUNNER_IMAGE
  value: quay.io/redhat-cop/anarchy-runner:v0.4.0
  #value: docker-registry.default.svc:5000/anarchy-operator/anarchy-runner:latest
  #value: image-registry.openshift-image-registry.svc:5000/anarchy-operator/anarchy-runner:latest
- name: RUNNER_IMAGE_PULL_POLICY
  value: IfNotPresent
  #value: Always
- name: DEFAULT_RUNNER_TOKEN
  description: Token use to validate anarchy runner to anarchy operator
  displayName: Default Runner Token
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  required: true

objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${NAME}

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: ${NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: anarchy-operator
  subjects:
  - kind: ServiceAccount
    name: ${NAME}

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: ${NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${NAME}
      spec:
        containers:
        - name: manager
          env:
          - name: ANARCHY_SERVICE
            value: ${NAME}
          - name: CALLBACK_BASE_URL
            value: https://${OPERATOR_HOSTNAME}
          - name: RUNNER_IMAGE
            value: ${RUNNER_IMAGE}
          - name: RUNNER_IMAGE_PULL_POLICY
            value: ${RUNNER_IMAGE_PULL_POLICY}
          image: ${OPERATOR_IMAGE}
          imagePullPolicy: ${OPERATOR_IMAGE_PULL_POLICY}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        restartPolicy: Always
        securityContext: {}
        serviceAccountName: ${NAME}
        terminationGracePeriodSeconds: 30

- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
  spec:
    ports:
    - name: api
      port: 5000
      protocol: TCP
      targetPort: 5000
    - name: metrics
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      name: ${NAME}
    sessionAffinity: None
    type: ClusterIP

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${NAME}
  spec:
    host: ${OPERATOR_HOSTNAME}
    port:
      targetPort: api
    tls:
      termination: edge
    to:
      kind: Service
      name: ${NAME}

- apiVersion: anarchy.gpte.redhat.com/v1
  kind: AnarchyRunner
  metadata:
    name: default
  spec:
    ansibleGalaxyRoles: []
    minReplicas: 1
    maxReplicas: 9
    preTasks: []
    postTasks: []
    resources:
      limits:
        cpu: "1"
        memory: 256Mi
      requests:
        cpu: 500m
        memory: 256Mi
    token: ${DEFAULT_RUNNER_TOKEN}
    vars: {}
    varSecrets: []
