---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: anarchy-operator install
  name: anarchy-operator-install

parameters:
- name: OPERATOR_DOMAIN
  description: Anarchy operator custom resource definition domain
  displayName: Anarchy operator CRD domain
  value: anarchy.gpte.redhat.com

objects:
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: anarchyactions.${OPERATOR_DOMAIN}
  spec:
    group: ${OPERATOR_DOMAIN}
    version: v1
    scope: Namespaced
    names:
      plural: anarchyactions
      singular: anarchyaction
      kind: AnarchyAction
      shortNames: []
    subresources:
      status: {}

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: anarchygovernors.${OPERATOR_DOMAIN}
  spec:
    group: ${OPERATOR_DOMAIN}
    version: v1
    scope: Namespaced
    names:
      plural: anarchygovernors
      singular: anarchygovernor
      kind: AnarchyGovernor
      shortNames: []
    subresources:
      status: {}

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: anarchyrunners.${OPERATOR_DOMAIN}
  spec:
    group: ${OPERATOR_DOMAIN}
    version: v1
    scope: Namespaced
    names:
      plural: anarchyrunners
      singular: anarchyrunner
      kind: AnarchyRunner
      shortNames: []
    subresources:
      status: {}

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: anarchyruns.${OPERATOR_DOMAIN}
  spec:
    group: ${OPERATOR_DOMAIN}
    version: v1
    scope: Namespaced
    names:
      plural: anarchyruns
      singular: anarchyrun
      kind: AnarchyRun
      shortNames: []
    subresources:
      status: {}

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: anarchysubjects.${OPERATOR_DOMAIN}
  spec:
    group: ${OPERATOR_DOMAIN}
    version: v1
    scope: Namespaced
    names:
      plural: anarchysubjects
      singular: anarchysubject
      kind: AnarchySubject
      shortNames: []
    subresources:
      status: {}

- kind: ClusterRole
  apiVersion: v1
  metadata:
    name: anarchy-operator
    labels:
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
  rules:
  - apiGroups:
    - ${OPERATOR_DOMAIN}
    resources:
    - anarchygovernors
    - anarchyrunners
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ${OPERATOR_DOMAIN}
    resources:
    - anarchyactions
    - anarchyactions/status
    - anarchyrunners
    - anarchyrunners/status
    - anarchyruns
    - anarchyruns/status
    - anarchysubjects
    - anarchysubjects/status
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - apps
    resources:
    - deployments
    - deployments/rollback
    - deployments/scale
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
  - apiGroups:
    - image.openshift.io
    resources:
    - imagestreams
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - route.openshift.io
    resources:
    - routes
    verbs:
    - create
    - get
    - list
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - pods
    - secrets
    - serviceaccounts
    - services
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
    - update

- kind: ClusterRole
  apiVersion: v1
  metadata:
    name: anarchy-operator-admin
    labels:
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
  rules:
  - apiGroups:
    - ${OPERATOR_DOMAIN}
    resources:
    - anarchygovernors
    - anarchyrunners
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
