---
- block:
  - name: Load AnarchyEvent vars for {{ anarchy_event_name }}
    include_vars: "{{ playbook_dir }}/vars/{{ anarchy_event_name }}.yml"

  - name: Run AnarchyEvent tasks for {{ anarchy_event_name }}
    include_tasks: "{{ playbook_dir }}/tasks/{{ anarchy_event_name }}.yml"

  - name: Update AnarchyEvent status to complete
    anarchy_event_update:
      name: "{{ anarchy_event_name }}"
      metadata:
        labels: >-
          {{ { anarchy_runner_label: 'success-' + anarchy_runner_name } }}
      spec:
        lastRun: "{{ anarchy_runner_timestamp }}"
        log: >-
          {{ anarchy_event.spec.log | default([]) + [{
            'runner': anarchy_runner_name,
            'result': 'success',
            'timestamp': anarchy_runner_timestamp
          }] }}

  rescue:
  - name: Update AnarchyEvent status on error
    anarchy_event_update:
      name: "{{ anarchy_event_name }}"
      metadata:
        labels: >-
          {{ { anarchy_runner_label: 'failed-' + anarchy_runner_name } }}
      spec:
        failures: >-
          {{ anarchy_event_status.failures|default(0)|int + 1 }}
        lastRun: "{{ anarchy_runner_timestamp }}"
        log: >-
          {{ anarchy_event.spec.log | default([]) + [{
            'runner': anarchy_runner_name,
            'result': 'failed',
            'timestamp': anarchy_runner_timestamp
          }] }}
