---
apiVersion: gpte.redhat.com/v1
kind: AnarchyAPI
metadata:
  name: babylon1
  namespace: anarchy-operator
spec:
  baseUrl: https://tower1.babylon1.example.opentlc.com
  basicAuth:
    secretName: babylon1-api-creds
  caCertificate: ""
  callbackEventNameParameter: event
  callbackTokenParameter: babylon_callback_token
  callbackUrlParameter: babylon_callback_url
  data: '{{: { "extra_vars": parameters } | to_json :}}'
  parameters:
    babylon_deployer_action: '{{: parameters.ACTION :}}'
  path: /api/v2/job_templates/job-runner/launch/
  headers:
  - name: Content-type
    value: application/json
  method: POST
