---
apiVersion: anarchy.gpte.redhat.com/v1
kind: AnarchyAPI
metadata:
  name: ${TOWER_NAME}
  namespace: anarchy-operator
spec:
  baseUrl: ${TOWER_URL}
  basicAuth:
    secretName: ${TOWER_NAME}-api-creds
  caCertificate: ${TOWER_CERT}
  callbackEventNameParameter: event
  data: >-
    {{: {
      'extra_vars': {
        'job_vars': parameters | combine({
          '__meta__': {
            'callback': {
              'token': action.callback_token,
              'url': action.callback_url
            },
            'deployer': {
              'entry_point': action_config.vars.deployer_entry_point
            },
            'tower': {
              'action': action_config.name
            }
          }
        })
      }
    } | to_json :}}
  headers:
  - name: Content-type
    value: application/json
  method: POST
  path: /api/v2/job_templates/job-runner/launch/
