---
apiVersion: anarchy.gpte.redhat.com/v1
kind: AnarchyGovernor
metadata:
  name: reqres-in-example
spec:
  parameters: {}
  subjectEventHandlers:
  - event: add
    handlers:
    - type: scheduleAction
      action: register
  - event: modify
    handlers:
    - type: scheduleAction
      action: update
  - event: delete
    handlers:
    - type: scheduleAction
      action: delete
  actions:
  - name: register
    request:
      api: reqres.in
      path: /api/register
      method: POST
      statusCodeEvents:
        200: registered
    eventHandlers:
    - event: registered
      handlers:
      - type: scheduleAction
        action: check
        after: 1m
      - type: setLabels
        setLabels:
        - name: userid
          jinja2Template: "{{ response.json.data.id }}"
      - type: setStatus
        setStatus:
        - name: userId
          jinja2Template: '{{ action.status.apiResponse.data.id }}'
  - name: check
    api:
      url: "https://reqres.in/api/users/{{ subject.status.userId }}"
      statusCodeEvents:
        200: okay
        404: not_found
    eventHandlers:
    - event: okay
      handlers:
      - type: scheduleAction
        action: check
        after: 1m
    - event: not_found
      handlers:
      - type: scheduleAction
        action: register
  - name: update
    api:
      url: "https://reqres.in/api/users/{{ subject.status.userId }}"
      request:
        method: PUT
      statusCodeEvents:
        200: okay
    eventHandlers:
    - event: okay
      handlers:
      - type: setStatus
        updatedAt: "{{ response.json.updatedAt }}"
  - name: delete
    api:
      url: "https://reqres.in/api/users/{{ subject.status.userId }}"
      request:
        method: DELETE
      statusCodeEvents:
        200: okay
        404: not_found
    eventHandlers:
    - event: okay
      handlers:
      - type: scheduleAction
        action: check
        after: 1m
    - event: not_found
      handlers:
      - type: scheduleAction
        action: register
        after: 5m
