---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: anarchy-operator babylon integration
  name: anarchy-operator-babylon-integration

parameters:
- name: ANARCHY_NAMESPACE
  value: anarchy-operator
- name: TOWER_NAME
  description: Name of the target tower cluster
  value: babylon
- name: TOWER_URL
  description: Base URL of the target tower cluster
  required: true
- name: TOWER_CA_CERT
  description: >-
    TLS certificate authority to validate tower server identity. Set to empty
    string to disable TLS certificate checking
- name: TOWER_USER
  description: User name for tower authentication
  required: true
- name: TOWER_PASSWORD
  description: Password for tower authentication
  required: true

objects:
- apiVersion: anarchy.gpte.redhat.com/v1
  kind: AnarchyAPI
  metadata:
    name: ${TOWER_NAME}
    namespace: ${ANARCHY_NAMESPACE}
  spec:
    baseUrl: ${TOWER_URL}
    basicAuth:
      secretName: ${TOWER_NAME}-api-creds
    caCertificate: ${TOWER_CA_CERT}
    callbackEventNameParameter: event
    data: >-
      {{: {
        'extra_vars': {
          'job_vars': parameters | combine({
            '__meta__': {
              'callback': {
                'token': action.callback_token,
                'url': action.callback_url
              },
              'deployer': {
                'entry_point': action_config.vars.deployer_entry_point
              },
              'tower': {
                'action': action_config.name,
                'organization': governor.vars.tower_organization
              }
            }
          })
        }
      } | to_json :}}
    headers:
    - name: Content-type
      value: application/json
    method: POST
    path: /api/v2/job_templates/job-runner/launch/

- apiVersion: v1
  kind: Secret
  metadata:
    name: ${TOWER_NAME}-api-creds
    namespace: ${ANARCHY_NAMESPACE}
  stringData:
    user: ${TOWER_USER}
    password: ${TOWER_PASSWORD}
