- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    pod: "{{ lookup('env', 'POD_NAME') }}"
    success_callback_url: "{{ lookup('env', 'SUCCESS_CALLBACK_URL') }}"
    error_callback_url: "{{ lookup('env', 'ERROR_CALLBACK_URL') }}"
  tasks:
  - block:
    - name: Read contents of /run/secrets/kubernetes.io/serviceaccount/ca.crt
      slurp:
        src: /run/secrets/kubernetes.io/serviceaccount/ca.crt
      register: slurp_ca_crt

    - name: Read contents of /run/secrets/kubernetes.io/serviceaccount/namespace
      slurp:
        src: /run/secrets/kubernetes.io/serviceaccount/namespace
      register: slurp_namespace

    - name: Read contents of /run/secrets/kubernetes.io/serviceaccount/token
      slurp:
        src: /run/secrets/kubernetes.io/serviceaccount/token
      register: slurp_token

    - name: Write kubeconfig
      copy:
        content: "{{ kubeconfig | to_nice_yaml }}"
        dest: "{{ lookup('env', 'KUBECONFIG') }}"
      vars:
        kubeconfig:
          apiVersion: v1
          clusters:
          - name: cluster
            cluster:
              certificate-authority-data: "{{ slurp_ca_crt['content'] }}"
              server: https://kubernetes.default.svc.cluster.local
          contexts:
          - name: ansible
            context:
              cluster: cluster
              namespace: "{{ slurp_namespace['content'] | b64decode }}"
              user: ansible
          current-context: ansible
          users:
          - name: ansible
            user:
              token: "{{ slurp_token['content'] | b64decode }}"

    - name: Set fact for callback data
      set_fact:
        callback_data: {}

    - name: Include vars
      include_vars: dynamic/vars.yaml

    - name: Include tasks
      include_tasks: dynamic/tasks.yaml

    - name: Success callback
      uri:
        url: "{{ success_callback_url }}"
        method: POST
        body:
          pod: "{{ pod }}"
          callback_data: "{{ callback_data }}"
        body_format: json
      when: success_callback_url

    rescue:
    - name: Error callback
      uri:
        url: "{{ error_callback_url }}"
        method: POST
        body:
          pod: "{{ pod }}"
          ansible_failed_task: "{{ ansible_failed_task }}"
          ansible_failed_result: "{{ ansible_failed_result }}"
        body_format: json
      when: error_callback_url
