---
apiVersion: anarchy.gpte.redhat.com/v1
kind: AnarchyGovernor
metadata:
  name: gitops
spec:
  ansibleGalaxyRequirements:
    collections: []
    roles:
    - name: k8s_config
      src: git+https://github.com/redhat-gpte-devopsautomation/k8s_config.git
      version: 0.1.4
  runner: default
  vars:
    # Interval for processing
    # Should be specified as a positive number folled by 'd', 'h', or 'm'
    # for units of 'day', 'hour', or 'minute'
    run_interval: 1h

    # Configuration sources
    k8s_config_sources: []

  subjectEventHandlers:
    create:
      tasks:
      - name: Schedule Deploy
        anarchy_schedule_action:
          action: configure
    update:
      tasks:
      - name: Schedule Deploy
        anarchy_schedule_action:
          action: configure

  actions:
    configure:
      roles:
      - k8s_config
      tasks:
      - name: Schedule next run
        anarchy_schedule_action:
          action: configure
          after: "{{ run_interval }}"
