---
- name: GitOps Setup
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
  - name: Get cluster ingress configuration
    k8s_info:
      api_version: config.openshift.io/v1
      kind: Ingress
      name: cluster
    register: _k8s_info_get_cluster_ingress

  - name: Get anarchy-k8s-config default AnarchyRunner
    k8s_info:
      api_version: anarchy.gpte.redhat.com/v1
      kind: AnarchyRunner
      name: default
      namespace: k8s-gitops
    register: _k8s_info_get_anarchy_k8s_config_default_anarchy_runner

  - name: Set k8s_info fact
    set_fact:
      k8s_info:
        cluster_ingress_domain: >-
          {{ _k8s_info_get_cluster_ingress.resources[0].spec.domain }}
        anarchy_k8s_config_default_runner_token: >-
          {{ _k8s_info_get_anarchy_k8s_config_default_anarchy_runner.resources[0].spec.token
           | default(lookup('password', '/dev/null length=15 chars=ascii_letters')) }}

  roles:
  - role: k8s_config
    vars:
      k8s_config_environment_level: dev

      # Configuration sources
      k8s_config_sources:
      - name: k8s-config
        base_path: examples/gitops/k8s-config
        git:
          repo: https://github.com/redhat-gpte-devopsautomation/anarchy-operator.git
